### ISSUE TITLE
Error getting the Synapse server name using `GET /_matrix/key/v2/server`

### ISSUE THREAD

**Issue by drygdryg** [verdigado/rocketchat2matrix#18]
Matrix-synapse version: 1.110.0
Stdout:
```
…
info: Parsing message with ID: 00310bf6-24fb-4bde-819d-f74bd8762a78
error: Error during request: Request failed with status code 404
error: Request: GET /_matrix/key/v2/server
error: Response: 404 {"errcode":"M_UNRECOGNIZED","error":"Unrecognized request"}
```

This error occurs here: https://github.com/verdigado/rocketchat2matrix/blob/5bb8bb8d566d5fd18a0b257bed38ec7c37ddbe3f/src/helpers/synapse.ts#L85

I tried to reproduce the request manually, and got the same error:
```
$ curl https://***********/_matrix/client/v3/server -H 'Authorization: Bearer syt_**********************'
{"errcode":"M_UNRECOGNIZED","error":"Unrecognized request"}
```
Perhaps this API endpoint was removed in the latest version of the Matrix specification. Is there any alternative way to get the server name?

**Comment by HerHde** [comment]
As far as I can see, the latest Matrix spec version contains the [endpoint](https://spec.matrix.org/latest/server-server-api/#get_matrixkeyv2server) and it has been there for quite some time (same link works since v1.6).

The example you used for reproduction contains a different URL:

```diff
- /_matrix/key/v2/server
+ /_matrix/client/v3/server
```

We're using the same synapse version in the dev and CI setup. The only ideas I have right now are:

- Are you running a different config, reverse proxy or anything that might interfere with the path?
- This is the only request to the server API instead of the client API iirc. Could you please try another endpoint from the [server-server API](https://spec.matrix.org/v1.11/server-server-api/), like `/_matrix/federation/v1/version` and/or anything else?

**Comment by drygdryg** [comment]
> * Are you running a different config, reverse proxy or anything that might interfere with the path?

Yes, the "federation" resource was disabled in my `homeserver.yaml`:
```
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client]
        compress: false
```
Thanks for your help  and sorry for bothering you unnecessarily.

**Comment by HerHde** [comment]
No bother at all! You brought up an important case!
I do consider using the username from `whois` for a (hopefully) more reliable hostname detection, now.

**Comment by HerHde** [comment]
I've changed the endpoint for `getServername()` to `whois` in 79081c79c9cdb942bee614fe3a639fac1e30b045 under the assumption that the admin user is a local one (which is the case, following the instructions). Therefore, this should not cause any more problems.
